accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import (login_view,
                            register_view,
                            logout_view,
                            profile_update,
                            profile_detail,
                            show_another_profile,
                            profile_following_space,
                            follow_profile)

app_name = "accounts"
urlpatterns = [
    url(r'^login/$', login_view, name="login"),
    url(r'^register/$', register_view, name="register"),
    url(r'^logout/$', logout_view, name="logout"),
    url(r'^profile/edit/', profile_update, name="edit"),
    url(r'^profile/', profile_detail, name="profile"),
    url(r'^showprofile/(?P<id>[\w-]+)', show_another_profile, name="showprofile"),
    url(r'^profilefollowing/(?P<id>[\w-]+)', profile_following_space, name="profilefollowingspace"),
    url(r'^follow/(?P<id>[\w-]+)', follow_profile, name='followprofile'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ask/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from ask.views import (question_create,
                       question_detail,
                       question_index,
                       profile_questions_list,
                       upvote_question,
                       downvote_question,
                       question_delete,
                       question_update)

app_name = "ask"
urlpatterns = [
    url(r'^home/$', question_index, name="home"),
    url(r'^myquestions/$', profile_questions_list, name="myquestions"),
    url(r'^create/$', question_create, name='create'),
    url(r'^upvote/(?P<slug>[\w-]+)/$', upvote_question, name='upvote'),
    url(r'^downvote/(?P<slug>[\w-]+)/$', downvote_question, name='downvote'),
    url(r'^(?P<slug>[\w-]+)/$', question_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/update/$', question_update, name="update"),
    url(r'^(?P<slug>[\w-]+)/delete/$', question_delete, name='delete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from ask.views import question_index

app_name = "question"
urlpatterns = [

    path('admin/', admin.site.urls),
    path('', question_index, name="home"),
    path('question/', include('ask.urls')),
    path('accounts/', include('accounts.urls')),
    path('spaces/', include('spaces.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spaces/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from spaces.views import (space_create,
                          space_index,
                          follow_space,
                          space_question_create,
                          space_detail,
                          space_question_detail,
                          space_question_delete,
                          space_question_update,
                          upvote_question,
                          downvote_question
                          )
app_name = "space"
urlpatterns = [
    url(r'^create/', space_create, name='create'),
    url(r'^spacelist/$', space_index, name='listspace'),
    url(r'^follow/(?P<slug>[\w-]+)$', follow_space, name='follow'),
    url(r'^detail/(?P<slug>[\w-]+)$', space_detail, name='spacedetail'),
    url(r'^upvote/(?P<slug>[\w-]+)/$', upvote_question, name='upvote'),
    url(r'^downvote/(?P<slug>[\w-]+)/$', downvote_question, name='downvote'),
    url(r'^qdetail/(?P<slug>[\w-]+)', space_question_detail, name='detail'),
    url(r'^update/(?P<slug>[\w-]+)', space_question_update, name="update"),
    url(r'^delete/(?P<slug>[\w-]+)', space_question_delete, name='delete'),
    url(r'^(?P<slug>[\w-]+)', space_question_create, name='askinspace'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.urls import reverse
from spaces.models import Spaces
from ask.models import Question, SpaceQuestion

class Profile(models.Model):
    GENDER_MALE = 1
    GENDER_FEMALE = 2
    GENDER_CHOICES = [
        (GENDER_MALE, _("Male")),
        (GENDER_FEMALE, _("Female")),
    ]

    user = models.ForeignKey(User, related_name="profile", on_delete=models.CASCADE)
    following = models.ManyToManyField(Spaces, related_name="following", blank=True)
    profile_pic = models.ImageField(upload_to="profiles", null=True, blank=True, default='default.jpg')
    birthday = models.DateField(null=True, blank=True, verbose_name="birthday")
    gender = models.PositiveSmallIntegerField(choices=GENDER_CHOICES, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    following_user = models.ManyToManyField(User, related_name="following_user", blank=True)
    follower_user = models.ManyToManyField(User, related_name="follower_user",  blank=True)
    upvoting = models.ManyToManyField(Question, related_name="upvoting", blank=True)
    downvoting = models.ManyToManyField(Question, related_name="downvoting", blank=True)
    upvotingsq = models.ManyToManyField(SpaceQuestion, related_name="upvotingsq", blank=True)
    downvotingsq = models.ManyToManyField(SpaceQuestion, related_name="downvotingsq", blank=True)


    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('accounts:profile')


    @property
    def image_url(self):
        if self.profile_pic and hasattr(self.profile_pic, 'url'):
            return self.profile_pic.url

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from accounts.models import Profile


class LoginForm(forms.Form):# bir modelden bağımsız form geliştirmek istiyorsak Modelform yerine form
    username = forms.CharField(max_length=50, label="kullanıcı adı")
    password = forms.CharField(max_length=50, label="parola", widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("Kullanıcı adını veya şifreyi yanlış girdiniz!")
        return super(LoginForm, self).clean()

class RegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=100, label='Kullanıcı Adı')
    password1 = forms.CharField(max_length=100, label='Parola', widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=100, label='Parola Doğrulama', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = [
            'username',
            'password1',
            'password2',
        ]
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Şifreler eşleşmiyor!")
        return password2


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)
    email = forms.EmailField()
    class Meta:
        model = Profile
        fields = [
            'first_name',
            'last_name',
            'email',
            'profile_pic',
            'birthday',
            'city',
        ]

accounts/views.py
from django.shortcuts import render, Http404
from django.contrib.auth.models import User
from .forms import LoginForm, RegisterForm, ProfileForm
from django.contrib.auth import authenticate, login, logout
from accounts.models import Profile
from django.shortcuts import HttpResponseRedirect, redirect,get_object_or_404


def login_view(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('ask:home')
    return render(request, "account_form.html", {"form": form, 'title': 'Giriş Yap'})


def register_view(request):
    form = RegisterForm(request.POST or None)
    profile = Profile()
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password1')
        user.set_password(password)
        user.save()
        new_user = authenticate(username=user.username, password=password)
        profile.user = user
        profile.save()
        login(request, new_user)
        return redirect('accounts:edit')
    return render(request, "account_form.html", {"form": form, 'title': 'Üye Ol','profile': profile})

def logout_view(request):
    logout(request)
    return redirect('accounts:login')

def profile_detail(request):
    profile = Profile.objects.get(user=request.user)
    return render(request, 'profile_detail.html', {'profile': profile})

def profile_update(request):
    if not request.user.is_authenticated:
        raise Http404()
    profiles = Profile.objects.get(user=request.user)
    form = ProfileForm(request.POST or None, request.FILES, instance=profiles)
    if form.is_valid():
        profile = form.save()
        profile.user.first_name = form.cleaned_data.get('first_name')
        profile.user.last_name = form.cleaned_data.get('last_name')
        profile.user.email = form.cleaned_data.get('email')
        profile.user.save()
        form.save()
        return HttpResponseRedirect(profile.get_absolute_url())
    context = {
        'form': form,
    }
    return render(request, 'edit_profile.html', context)


def follow_profile(request, id):
    profile = Profile.objects.get(user=request.user)
    other = Profile.objects.get(id=id)
    user = User.objects.get(id=id)

    if other.user != profile.user and other.user in profile.following_user.all():
        follow = False
        profile.following_user.remove(other.user)
        other.follower_user.remove(profile.user)
    elif other.user != profile.user and not other.user in profile.following_user.all():
        follow = True
        profile.following_user.add(other.user)
        other.follower_user.add(profile.user)
    if other.user in profile.following_user.all():
        follow = True
    else:
        follow = False
    context = {
        'other': other,
        'user': user,
        'follow': follow,
    }
    return render(request, 'show_profile.html', context)


def show_another_profile(request, id):
    user = User.objects.get(id=id)
    profile = Profile.objects.get(user=request.user)
    other = Profile.objects.get(id=id)

    if other.user in profile.following_user.all():
        follow = True
    else:
        follow = False

    return render(request, 'show_profile.html', {'user': user, 'follow': follow, 'other':other})


def profile_following_space(request,id):
    following = get_object_or_404(Profile, id=id).following.all()
    profile = Profile.objects.get(id=id)
    follows = profile.following_user.all()
    followers = profile.follower_user.all()
    context = {

        'following': following,
        'profile': profile,
        'follows': follows,
        'followers': followers
    }
    return render(request, 'following.html', context)

templates/add_comment.html
{% load crispy_forms_tags %}


    <div class="container">
    <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <form method="post" style="width: 500px">
                    {% csrf_token %}
                    {{ form|crispy }}
                </form>
            </div>
    </div>
    </div>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Quora</title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href=" {% static 'css/bootstrap.min.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    </head>

    <body>
        {% include 'header.html' %}

        {% block body %}

        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
                integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
                integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
                crossorigin="anonymous"></script>
    </body>
</html>

templates/following_space_questions.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

<!DOCTYPE html>

<html lang="en">
{% block body%}

<div class="container" style=" padding-left: 60px; padding-right: 50px">
  <div class="row">
    <div class="col-md" style="padding-top: 50px">

        {% for space in space_list %}
            <a href="{% url 'space:askinspace' slug=space.slug %} }}">
            <button type="button"  class="btn btn-light position-relative" style="width: 250px; text-transform: capitalize">
            {{ space.title }}
            </button>
            </a>
        <div style="padding-bottom: 1px"></div>
            <br>
         {% endfor %}
    </div>
    <div class="col-md"  style="padding-top: 50px">

                <div style="padding-bottom: 30px"></div>

                {% for question in following_space_questions %}
                        <div class="card" style="width: 40rem; height: auto" >
                          <div class="card-body" style="background-color : #ffffff;">
                           <small>{{ question.user.get_full_name }} asked</small>

                          {% if question in space_question_list.all %}
                              in <small style="text-transform: uppercase">{{ question.category}}</small>
                               <a  href="{% url 'space:detail' slug=question.slug %}" style="color: #000000; text-decoration-line: none">
                                 <h5 class="card-title">{{ question.question }}</h5><br>
                            </a>
                               <br><br>
                                 <p align="left">
                                <a href="{% url 'space:detail' slug=question.slug %}" >
                                    <svg width="24px" height="24px" viewBox="0 0 24 24"><g id="comment"  class="icon_svg-stroke icon_svg-fill" stroke="#666" stroke-width="2" fill="none" fill-rule="evenodd"><path d="M12.0711496,18.8605911 C16.1739904,18.8605911 19.5,15.7577921 19.5,11.9302955 C19.5,8.102799 16.1739904,5 12.0711496,5 C7.96830883,5 4.64229922,8.102799 4.64229922,11.9302955 C4.64229922,13.221057 5.02055525,14.429401 5.67929998,15.4641215 C5.99817082,15.9649865 4.1279592,18.5219189 4.56718515,18.9310749 C5.02745574,19.3598348 7.80252458,17.6358115 8.37002246,17.9406001 C9.45969688,18.5258363 10.7235179,18.8605911 12.0711496,18.8605911 Z"></path></g></svg>
                                </a>
                              </p>
                              {% if question.user == request.user %}
                              <a href="{% url 'space:delete' slug=question.slug %}" style="float: right">
                                   <button type="button"  class="btn btn-dark position-relative" style="width: 100px; text-transform: capitalize">
                                  delete </button>
                              </a>

                              <a href="{% url 'space:update' slug=question.slug %}" style="float: right">
                                  <button type="button"  class="btn btn-secondary position-relative" style="width: 100px;  text-transform: capitalize">
                                  update </button>
                              </a>
                              {% endif %}

                          {% else %}
                               <a  href="{% url 'ask:detail' slug=question.slug %}" style="color: #000000; text-decoration-line: none">
                                 <h5 class="card-title">{{ question.question }}</h5><br>
                                </a>
                               <br><br>
                                 <p align="left">
                                <a href="{% url 'ask:detail' slug=question.slug %}" >
                                    <svg width="24px" height="24px" viewBox="0 0 24 24"><g id="comment"  class="icon_svg-stroke icon_svg-fill" stroke="#666" stroke-width="2" fill="none" fill-rule="evenodd"><path d="M12.0711496,18.8605911 C16.1739904,18.8605911 19.5,15.7577921 19.5,11.9302955 C19.5,8.102799 16.1739904,5 12.0711496,5 C7.96830883,5 4.64229922,8.102799 4.64229922,11.9302955 C4.64229922,13.221057 5.02055525,14.429401 5.67929998,15.4641215 C5.99817082,15.9649865 4.1279592,18.5219189 4.56718515,18.9310749 C5.02745574,19.3598348 7.80252458,17.6358115 8.37002246,17.9406001 C9.45969688,18.5258363 10.7235179,18.8605911 12.0711496,18.8605911 Z"></path></g></svg>
                                </a>
                              </p>
                                {% if question.user == request.user %}
                              <a href="{% url 'ask:delete' slug=question.slug %}" style="float: right">
                                   <button type="button"  class="btn btn-dark position-relative" style="width: 100px; text-transform: capitalize">
                                  delete </button>
                              </a>

                              <a href="{% url 'ask:update' slug=question.slug %}" style="float: right">
                                  <button type="button"  class="btn btn-secondary position-relative" style="width: 100px;  text-transform: capitalize">
                                  update </button>
                              </a>
                              {% endif %}
                          {% endif %}

                          </div>
                        </div>
                        <div style="padding-bottom: 25px"></div>
                {% endfor %}


    </div>


    <div class="col-md" style="padding-top: 50px">

    </div>
  </div>
</div>
</div>
{% endblock %}
 </html>

templates/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

<!DOCTYPE html>

<html lang="en">
{% block body%}

<div class="container" style=" padding-left: 60px; padding-right: 50px">
  <div class="row">
    <div class="col-md" style="padding-top: 50px">
            <button type="button" class="btn btn-primary" style="width: 250px" data-bs-toggle="modal" data-bs-target="#exampleModal">
                +Create Space{{ upvote }}
                </button>
            <div style="padding-bottom: 5px"></div>
            <br>
<!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Create Space</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                      <form method="POST" class="uniForm" enctype="multipart/form-data">
                        {% csrf_token %}
                         {{ form2|crispy }}
                        <br>
                        <input type="submit" class="btn btn-primary" type="submit" style="color: darksalmon" value="Gönder">
                    </form>
                  </div>
                </div>
              </div>
            </div>


        {% for space in space_list %}
            <div style="padding-top: 3px"></div>
            <a href="{% url 'space:askinspace' slug=space.slug %} }}">

            <button type="button" class="btn space_button position-relative" style="text-align: left">
            <img src="{{ space.image_url|default_if_none:'#' }}" width="30" height="30" style="border-radius: 30px"/>
                {{ space.title }}
            </button>
            </a>
            <br>
         {% endfor %}
    </div>
    <div class="col-md"  style="padding-top: 50px">
      <div class="card" style="width: 40rem;  height: 150px" >
              <div class="card-body" style="background-color: #ffffff">
                <form method="POST" class="uniForm" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1>Add Question</h1>
                     {{ form|crispy}}
                </form>
              </div>
            </div>
                <div style="padding-bottom: 2cm"></div>

                {% for question in combined_question %}
                        <div class="card" style="width: 40rem; height: auto" >
                          <div class="card-body" style="background-color : #ffffff;">
                           {% for profile in profiles %}
                               {% if question.user.id == profile.user.id %}
                                 <img src="{{ profile.image_url|default_if_none:'#' }}" width="30" height="30" style="border-radius: 30px ; float: left"/>
                               {% endif %}
                           {% endfor %}
                           <small>{{ question.user.get_full_name }} asked</small>
                          <small style="float: right">{{ question.publishing_date }}</small>

                          {% if question in space_question_list.all %}
                              in <small style="text-transform: uppercase">{{ question.category.title}}</small><br><br>
                               <a  href="{% url 'space:detail' slug=question.slug %}" style="color: #000000; text-decoration-line: none">
                                 <h5 class="card-title">{{ question.question }}</h5><br>
                            </a>
                              {% if question.picture %}
                                        <a href="{% url 'space:detail' slug=question.slug %}">
                                <p><img src="{{ question.picture.url }}" style="box-sizing: border-box; max-width: 100%; margin-left: auto; margin-right: auto;"> </p></a>
                                {% endif %}

                               <br><br>
                                 <p align="left">
                                <a href="{% url 'space:detail' slug=question.slug %}" >
                                    <svg width="24px" height="24px" viewBox="0 0 24 24"><g id="comment"  class="icon_svg-stroke icon_svg-fill" stroke="#666" stroke-width="2" fill="none" fill-rule="evenodd"><path d="M12.0711496,18.8605911 C16.1739904,18.8605911 19.5,15.7577921 19.5,11.9302955 C19.5,8.102799 16.1739904,5 12.0711496,5 C7.96830883,5 4.64229922,8.102799 4.64229922,11.9302955 C4.64229922,13.221057 5.02055525,14.429401 5.67929998,15.4641215 C5.99817082,15.9649865 4.1279592,18.5219189 4.56718515,18.9310749 C5.02745574,19.3598348 7.80252458,17.6358115 8.37002246,17.9406001 C9.45969688,18.5258363 10.7235179,18.8605911 12.0711496,18.8605911 Z"></path></g></svg>
                                </a>
                              </p>
                              {% if question.user == request.user %}
                              <a href="{% url 'space:delete' slug=question.slug %}" style="float: right">
                                   <button type="button"  class="btn btn-dark position-relative" style="width: 100px; text-transform: capitalize">
                                  delete </button>
                              </a>

                              <a href="{% url 'space:update' slug=question.slug %}" style="float: right">
                                  <button type="button"  class="btn btn-secondary position-relative" style="width: 100px;  text-transform: capitalize">
                                  update </button>
                              </a>
                              {% endif %}

                          {% else %}
                              <br><br>
                               <a  href="{% url 'ask:detail' slug=question.slug %}" style="color: #000000; text-decoration-line: none">
                                 <h5 class="card-title">{{ question.question }}</h5><br>
                                </a>
                             {% if question.picture %}
                                 <a href="{% url 'ask:detail' slug=question.slug %}">
                                <p><img src="{{ question.picture.url }}" style="box-sizing: border-box; max-width: 100%; margin-left: auto; margin-right: auto;"> </p></a>
                             {% endif %}

                               <br><br>
                                 <p align="left">
                                <a href="{% url 'ask:detail' slug=question.slug %}" >
                                    <svg width="24px" height="24px" viewBox="0 0 24 24"><g id="comment"  class="icon_svg-stroke icon_svg-fill" stroke="#666" stroke-width="2" fill="none" fill-rule="evenodd"><path d="M12.0711496,18.8605911 C16.1739904,18.8605911 19.5,15.7577921 19.5,11.9302955 C19.5,8.102799 16.1739904,5 12.0711496,5 C7.96830883,5 4.64229922,8.102799 4.64229922,11.9302955 C4.64229922,13.221057 5.02055525,14.429401 5.67929998,15.4641215 C5.99817082,15.9649865 4.1279592,18.5219189 4.56718515,18.9310749 C5.02745574,19.3598348 7.80252458,17.6358115 8.37002246,17.9406001 C9.45969688,18.5258363 10.7235179,18.8605911 12.0711496,18.8605911 Z"></path></g></svg>
                                </a>
                              </p>
                                {% if question.user == request.user %}
                              <a href="{% url 'ask:delete' slug=question.slug %}" style="float: right">
                                   <button type="button"  class="btn btn-dark position-relative" style="width: 100px; text-transform: capitalize">
                                  delete </button>
                              </a>

                              <a href="{% url 'ask:update' slug=question.slug %}" style="float: right">
                                  <button type="button"  class="btn btn-secondary position-relative" style="width: 100px;  text-transform: capitalize">
                                  update </button>
                              </a>
                              {% endif %}
                          {% endif %}

                          </div>
                        </div>
                        <div style="padding-bottom: 25px"></div>
                {% endfor %}


    </div>


    <div class="col-md" style="padding-top: 50px">

        <a href="#" class="btn btn-primary" style="width: 250px;" tabindex="-1" aria-disabled="true" role="button" data-bs-toggle="button">PROFILES</a>
        <div style="padding-top: 20px"></div>
        {% for user in users %}
             <a href="{% url 'accounts:showprofile' id=user.id %}">
             <button type="button"  class="btn btn-light position-relative" style="width: 250px;height: 40px ;text-transform: capitalize">
                {% for profile in profiles %}
                    {% if user.id == profile.id %}
                        <img src="{{ profile.image_url|default_if_none:'#' }}" width="30" height="30" style="border-radius: 30px ; float: left"/>
                    {% endif %}
                    {% endfor %}
            {{ user.get_full_name }}
            </button>
            </a>
        <div style="padding-bottom: 1px"></div>
            <br>
        {% endfor %}

    </div>
  </div>
</div>
</div>
{% endblock %}
 </html>

templates/main.html
{% extends 'temel.html' %}
{% load static %}
{% block title %}
    main page
{% endblock %}

{% block content %}
    hello world
{% endblock %}

{% block scripts %}
  <script src="{% static 'main.js' %}"></script>
{% endblock %}

templates/space_question_detail.html
{% extends 'base.html' %}
<!DOCTYPE html>
{% block body %}
 <div class="container">
        <div class="row">
            <div class="col">

            </div>
            <div class="col">
                     <div class="card" style="width: 40rem; height: auto" >
                          <div class="card-body" style="background-color : #ffffff;">
                           <small>{{ question.user.get_full_name }} asked</small>
                            <small style="float: right">{{ question.publishing_date }}</small>
                                 <h5 class="card-title">{{ question.question }}</h5><br>
                              {% if question.picture %}
                                  <a href="{% url 'space:detail' slug=question.slug %}">
                                <p><img src="{{ question.picture.url }}" style="box-sizing: border-box; max-width: 100%; margin-left: auto; margin-right: auto;"> </p></a>
                                {% endif %}
                                    vote={{ upvote }}

                              {% include 'add_comment.html' %}
                          <hr>
                              <form method="POST">
                                {% csrf_token %}
                                    {% if upvote %}
                                        <a href="{% url 'space:upvote' slug=question.slug  %}" class="btn btn-success active" role="button" data-mdb-toggle="button" aria-pressed="true">Upvoted</a>
                                    {% else %}
                                        <a href="{% url 'space:upvote'  slug=question.slug %}" class="btn btn-secondary active" role="button" data-mdb-toggle="button" aria-pressed="true">Upvote</a>                    {% endif %}

                                {% csrf_token %}
                                    {% if downvote %}
                                        <a href="{% url 'space:downvote' slug=question.slug  %}" class="btn btn-success active" role="button" data-mdb-toggle="button" aria-pressed="true">Downvoted</a>
                                    {% else %}
                                        <a href="{% url 'space:downvote'  slug=question.slug %}" class="btn btn-secondary active" role="button" data-mdb-toggle="button" aria-pressed="true">Downvote</a>                    {% endif %}
                              </form>
                              up={{ up_count }},down={{ down_count }}
                          </div>
                        </div>


    <ul class="list-group list-group-flush">
        {% for comment in question_comments %}
            <li class="list-group-item">{{ comment.content}}
                <br>
                {{ comment.created_date|timesince }} önce - {{ comment.user}} tarafından</li>
        {% endfor %}
    </ul>
            <div style="padding-bottom: 100px"></div>
            </div>
            <div class="col">

            </div>

        </div>

    </div>
{% endblock %}